version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: couriersync-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  couriersync-app:
    build: .
    container_name: couriersync-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      PORT: 8080
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      JWT_SECRET: ${JWT_SECRET}

  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - couriersync-app

  # Dashboard de Visualización Grafana
  grafana:
    image: grafana/grafana-oss:10.2.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  postgres-data: