server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET}  # Clave para firmar el token (32+ caracteres)
    expiration: 1800000

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: "CourierSync API"
    description: "API para la optimización de procesos logísticos. Feature 5: Pagos y Facturación."
    version: "v1.0.0"
  components:
    securitySchemes:
      bearer-key:
        type: http
        scheme: bearer
        bearerFormat: JWT