server:
  address: 0.0.0.0
  port: ${PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 1800000

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: "CourierSync API"
    description: "API para la optimización de procesos logísticos. Feature 5: Pagos y Facturación."
    version: "v1.0.0"
  components:
    securitySchemes:
      bearer-key:
        type: http
        scheme: bearer
        bearerFormat: JWT

couriersync:
  billing:
    cost-per-kg: 2500
    base-fee: 5000
    tax-rate: 0.19

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus" # Exponemos el endpoint de prometheus
  endpoint:
    health:
      show-details: always